services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    networks:
      - postgres-internal
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - redis-internal
    volumes:
      - redis_data:/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - redis
      - db
    restart: unless-stopped
    networks:
      - redis-internal
      - postgres-internal
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.server.rule=Host(`api.chess.gwilldan.xyz`)
      - traefik.http.routers.server.entrypoints=websecure
      - traefik.http.routers.server.tls=true
      - traefik.http.routers.server.tls.certresolver=le

volumes:
  redis_data:
  postgres_data:

networks:
  redis-internal:
    internal: true

  postgres-internal:
    internal: true

  proxy:
    external: true
